# config.yaml
general:
  domain: 2,42.1,3.5,43.1
  domainName: 'ribaute'
  time_start: 2025-08-05_0500
  time_end: 2025-08-06_1030
  crs: 3035
  use_sedoo_drive: False 
  root_data: /media/paugam/gast/AERIS_2/
hs:
  dir_data: ORIGIN/hotspots
  sats: ['']
event:
  dir_data: ORIGIN/fire_events 
  dir_geoJson: ORIGIN/fire_events/GeoJson
  dir_frp: ORIGIN/fire_events/FRP
  start_time: '2025-06-29_0000'
  mask_HS: mask_hs_600m_europe.nc
  eurostat: 'EUROSTAT/COMM_RG_01M_2016_3035.gpkg'
  cloudMask_mtg: "FCI/RASTER/cloudMask/"
postproc:
  dir_FWI:  AROME/FWI
  dir_WIND: AROME/FORECAST/WIND/

