# config.yaml
general:
  domain: 2.2,42.7,3.2,43.5
  domainName: 'RIBAUTE'
  crs: 3035
  use_sedoo_drive: False 
  root_data: /data/paugam/FET-TEST
hs:
  dir_data: ORIGIN/hotspots2025
  sats: ['']
event:
  dir_data: ORIGIN/RIBAUTE_fire_events 
  dir_geoJson: ORIGIN/RIBAUTE_fire_events/GeoJson
  dir_frp: ORIGIN/RIBAUTE_fire_events/FRP
  dir_cloudMask: ORIGIN/RASTER/cloudMask/
  start_time: '2025-08-05_1400'
  end_time: '2025-08-06_1200'
  mask_HS: /data/paugam/FET-TEST/HS-MASK/data_mask_buffer_3857.geojson
  osm_bndf: 'OSM_Boundaries/osm_MED_admin_muni_boundaries.gpkg'
  cloudMask_mtg: "FCI/RASTER/cloudMask/"
  dir_hs_log: "ORIGIN/RIBAUTE_fire_events/HS_log/"
postproc:
  dir_FWI:  AROME/FWI
  dir_WIND: AROME/FORECAST/WIND/

